services:
  alerts:
    image: ghcr.io/notlet/alerts:latest
    container_name: alertsbot
    build: .
    tty: true # For colored logs
    restart: unless-stopped
    env_file: .env
    volumes:
      - ./db:/alerts/db